### ISSUE TITLE
failing to run Goose on my system

### ISSUE THREAD

**Issue by PaulConyngham** [block-open-source/goose#61]
Goose is failing to run on my system.

In the terminal I am initialising the key as an environment variable like so:

export OPENAI_API_KEY=xxxxxx

I am getting the following error every time I run the project:

![Screen Shot 2024-09-12 at 8 33 39 am](https://github.com/user-attachments/assets/a3e93873-493a-41c5-a2a0-90c70da7e1e2)

The key is active and is being called. As you can see an update on OpenAi's side (The last time I tried using this key was for Goose today , the 12th of Sept 2024):

<img width="1423" alt="Screen Shot 2024-09-12 at 8 42 41 am" src="https://github.com/user-attachments/assets/112ddb88-416f-454e-9038-d9ece8973662">

Noticed we are using pipx so my python version should not be affecting this. But to test outside of this ran it in a python 3.12 conda env too and via the vanilla terminal

It would be great to see what is actually going on under the hood here with a verbose output flag for Goose, perhaps something like: goose session start -v

**Comment by baxen** [comment]
I think most likely this is because the API key does not have access to the model. We have some updates in progress to catch that and similar cases more clearly! Verbose mode is also a good idea here. 

To try to confirm this, if you have an openai with chatgpt enabled, you likely separately have to enable billing for the API at platform.openai.com. Do you see API credits remaining at https://platform.openai.com/settings/organization/billing/overview?

**Comment by baxen** [comment]
Did you have any luck with this? if you upgrade, square/exchange#48 should show a much more clear error message
